login_root:
    path:     /login
    defaults: { _controller: FrontEndBundle:Login:index }



front_end_homepage:
    path:     /home
    defaults: { _controller: FrontEndBundle:Default:index }



front_end_resto:
    path:     /restauration
    defaults: { _controller: FrontEndBundle:Restaurent:index }



front_end_club:
    path:     /club
    defaults: { _controller: FrontEndBundle:Club:index }

front_end_covoiturage:
    path:     /covoiturage
    defaults: { _controller: FrontEndBundle:Covoiturage:index }

front_end_revision:
    path:     /revision
    defaults: { _controller: FrontEndBundle:Revision:index }



